"""Writers: a :class:`SimulatedDataset` → tidy files in one of three formats.

Pure I/O (ARCHITECTURE "writers never generate"). One call emits the reading table
and every dimension/label table in the chosen format, plus two always-present
sidecars:

* ``manifest.json`` — the run's provenance: config echo, seed, row/unit counts,
  format, and the honest "synthetic, J1939 + physics" statement (so a dataset is
  self-describing about *how* it was made and that it is **not** real telemetry).
* ``dataset_dictionary.md`` — every output column → meaning, unit, and J1939 SPN
  where applicable, generated from the signal registry so it can't drift.

Formats:

* ``parquet`` — columnar, one ``.parquet`` per table (via pyarrow).
* ``csv`` — one ``.csv`` per table.
* ``duckdb`` — a single ``dataset.duckdb`` file with one table per frame.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

from ..anomalies import ANOMALY_TYPES
from ..signals import TIER1_SIGNALS, get_spec
from ..sim.simulate import SimulatedDataset

FORMATS: tuple[str, ...] = ("parquet", "csv", "duckdb")

# Output table name → attribute on SimulatedDataset.
_TABLES = ("readings", "units", "vehicle_classes", "regions", "contracts")


def _tables(ds: SimulatedDataset) -> dict[str, pd.DataFrame]:
    return {name: getattr(ds, name) for name in _TABLES}


def _write_parquet(tables: dict[str, pd.DataFrame], out: Path) -> None:
    for name, df in tables.items():
        df.to_parquet(out / f"{name}.parquet", index=False)


def _write_csv(tables: dict[str, pd.DataFrame], out: Path) -> None:
    for name, df in tables.items():
        df.to_csv(out / f"{name}.csv", index=False)


def _write_duckdb(tables: dict[str, pd.DataFrame], out: Path) -> None:
    import duckdb

    con = duckdb.connect(str(out / "dataset.duckdb"))
    try:
        for name, df in tables.items():
            con.register("_frame", df)
            con.execute(f"CREATE OR REPLACE TABLE {name} AS SELECT * FROM _frame")
            con.unregister("_frame")
    finally:
        con.close()


_WRITERS = {"parquet": _write_parquet, "csv": _write_csv, "duckdb": _write_duckdb}


def _anomaly_type_counts(ds: SimulatedDataset) -> dict[str, int]:
    """Row count per labeled defect type (ADR-016), for provenance."""
    if ds.readings.empty or "anomaly_type" not in ds.readings:
        return {atype: 0 for atype in ANOMALY_TYPES}
    counts = ds.readings["anomaly_type"].value_counts()
    return {atype: int(counts.get(atype, 0)) for atype in ANOMALY_TYPES}


def _manifest(ds: SimulatedDataset, fmt: str) -> dict:
    cfg = ds.config
    return {
        "generator": "can-telemetry-forge",
        "synthetic": True,
        "provenance": (
            "Synthetic data, modeled on the public SAE J1939 standard + documented "
            "physics for a fictional fleet operator. NOT real telemetry."
        ),
        "seed": cfg.seed,
        "resolution": cfg.resolution,
        "days": cfg.days,
        "failure_horizon_h": cfg.failure_horizon_h,
        "anomaly_rates": cfg.resolved_anomaly_rates(),
        "operator_name": cfg.fleet.operator_name,
        "format": fmt,
        "n_units": int(ds.units.shape[0]),
        "n_readings": int(ds.readings.shape[0]),
        "n_failure_rows": int(ds.readings["failure_within_h"].sum()) if not ds.readings.empty else 0,
        "n_outlier_rows": int(ds.readings["is_outlier"].sum()) if not ds.readings.empty else 0,
        "n_anomaly_rows_by_type": _anomaly_type_counts(ds),
    }


def _dataset_dictionary_md(ds: SimulatedDataset) -> str:
    lines = [
        "# Dataset dictionary (generated)",
        "",
        "Synthetic heavy-equipment telemetry — modeled on the public **SAE J1939**",
        "standard + documented physics. **Not real telemetry.** Generated by",
        "`can-telemetry-forge`. Era-gated signals are `NULL` (never zero) where a",
        "unit's CAN capability era does not support them.",
        "",
        "## `readings` (tidy long table)",
        "",
        "| Column | Unit | J1939 SPN | Meaning |",
        "|---|---|---|---|",
        "| `unit_id` | — | — | Unit identifier (FK → `units`). |",
        "| `t_index` | — | — | Reading index within the unit's window. |",
        "| `timestamp_h` | h | — | Hours since window start. |",
    ]
    for spec in TIER1_SIGNALS:
        spn = str(spec.spn) if spec.spn is not None else "—"
        lines.append(f"| `{spec.name}` | {spec.unit} | {spn} | {spec.description} |")
    lines += [
        "| `failure_within_h` | 0/1 | — | 1 if a failure occurs within the horizon. |",
        "| `failure_mode` | — | — | overheat / oil_starve / bearing (else empty). |",
        "| `is_outlier` | bool | — | True if the row carries a value-distorting "
        "defect (obvious/joint outlier or stuck/drift sensor fault). Back-compat rollup. |",
        "| `anomaly_type` | — | — | Labeled defect on the row (else empty): "
        + " / ".join(f"`{t}`" for t in ANOMALY_TYPES)
        + ". One per row by injector priority. |",
        "| `anomaly_signal` | — | — | Which signal carries the row's labeled defect "
        "(empty if none). |",
        "",
        "### Labeled defects (`anomaly_type`)",
        "",
        "Every injected defect is recoverable from these labels (ADR-006/-016). "
        "Era-`NULL` cells are never targeted — a sensor fault is a *healthy* channel "
        "going bad, distinct from structural era-missingness.",
        "",
        "- `obvious_outlier` — a single out-of-range spike (impossible on its own).",
        "- `joint_outlier` — each column in range but the **pair** is impossible "
        "(e.g. high fuel rate with near-zero load).",
        "- `sensor_stuck` — a channel frozen at one value over a contiguous segment.",
        "- `sensor_drift` — a slow accumulating bias on one channel over a segment.",
        "- `sensor_dropout` — a channel goes `NULL` over a segment (not era-gating).",
        "",
        "## Dimension tables",
        "",
        "- `units` — one row per machine (class, contract, region, build year, era, "
        "runtime/age at window start).",
        "- `vehicle_classes` — machinery classes and their duty/wear parameters.",
        "- `regions` — deployment geographies with public-grounded climate/terrain "
        "(see the `source` column).",
        "- `contracts` — jobs per region.",
        "",
        "_SPN ranges/units are the published SAE J1939-71 values; see "
        "`docs/DATA_DICTIONARY.md` for the full signal spec._",
    ]
    # get_spec referenced to keep the registry import meaningful for future columns.
    _ = get_spec
    return "\n".join(lines) + "\n"


def write_dataset(ds: SimulatedDataset, out_dir: str | Path, fmt: str = "parquet") -> Path:
    """Write ``ds`` to ``out_dir`` in ``fmt`` plus manifest + dictionary sidecars.

    Returns the output directory path. Creates it if needed.
    """
    if fmt not in FORMATS:
        raise ValueError(f"format {fmt!r} not in {FORMATS}")
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    _WRITERS[fmt](_tables(ds), out)

    (out / "manifest.json").write_text(
        json.dumps(_manifest(ds, fmt), indent=2), encoding="utf-8"
    )
    (out / "dataset_dictionary.md").write_text(_dataset_dictionary_md(ds), encoding="utf-8")
    return out


__all__ = ["FORMATS", "write_dataset"]
